export const propsMock = {
  boards: [
    {
      id: "ih2dfdf2",
      contents: "ㄴㄴㄴㄴㄴㄴ",
      createdAt: "2023.04.01. 15:37",
      date: "2023년 4월 1일 오후 3시 37분 29초 UTC+9",
      deletedAt: false,
      password: "1234",
      title: "한글오라와와와와와와와와와와와와와와와와",
      writer: "한글이름입니다앙",
    },
    {
      id: "nrfdhd89",
      contents: "ㄴㄴㄴㄴㄴㄴ",
      createdAt: "2023.04.02. 15:37",
      date: "2023년 4월 2일 오후 3시 37분 29초 UTC+9",
      deletedAt: false,
      password: "1234",
      title: "한글오라와와와와와와와와와와와와와와와와",
      writer: "한글이름입니다앙",
    },
    {
      id: "hkjjhkec4t",
      contents: "ㄴㄴㄴㄴㄴㄴ",
      createdAt: "2023.04.03. 15:37",
      date: "2023년 4월 3일 오후 3시 37분 29초 UTC+9",
      deletedAt: false,
      password: "1234",
      title: "한글오라와와와와와와와와와와와와와와와와",
      writer: "한글이름입니다앙",
    },
    {
      id: "sdfdsfsjhhj",
      contents: "ㄴㄴㄴㄴㄴㄴ",
      createdAt: "2023.04.04. 15:37",
      date: "2023년 4월 4일 오후 3시 37분 29초 UTC+9",
      deletedAt: false,
      password: "1234",
      title: "한글오라와와와와와와와와와와와와와와와와",
      writer: "한글이름입니다앙",
    },
    {
      id: "ikfnsidfods",
      contents: "ㄴㄴㄴㄴㄴㄴ",
      createdAt: "2023.04.05. 15:37",
      date: "2023년 4월 5일 오후 3시 37분 29초 UTC+9",
      deletedAt: false,
      password: "1234",
      title: "한글오라와와와와와와와와와와와와와와와와",
      writer: "한글이름입니다앙",
    },
  ],
  pathname: "/free-boards/",
  currentTopNumber: 5,
  lastPage: 1,
  isOpen: false,
  errorMessage: "",
  onClose: jest.fn(),
  onClickMoveToPage: jest.fn(),
  onClickNextButton: jest.fn(),
  onClickPrevButton: jest.fn(),
};
