export const propsWriteMock = {
  isEdit: false,
  writer: "",
  title: "",
  contents: "",
  isOpen: false,
  errorMessage: "",
  placeHolderWriter: "작성자명을 입력해주세요.",
  placeHolderPassword: "비밀번호를 입력해주세요.",
  placeHolderTitle: "제목을 입력해주세요.",
  placeHolderContents: "내용을 입력해주세요.",
  onChangeWriter: jest.fn(),
  onChangePassword: jest.fn(),
  onChangeTitle: jest.fn(),
  onChangeContents: jest.fn(),
  onClickSubmit: jest.fn(),
  onClickUpdate: jest.fn(),
  onClose: jest.fn(),
};

export const propsEditMock = {
  isEdit: true,
  writer: "홍길동",
  title: "게시글 제목",
  contents: "게시글 내용",
  isOpen: false,
  errorMessage: "",
  placeHolderWriter: "작성자명을 입력해주세요.",
  placeHolderPassword: "비밀번호를 입력해주세요.",
  placeHolderTitle: "제목을 입력해주세요.",
  placeHolderContents: "내용을 입력해주세요.",
  onChangeWriter: jest.fn(),
  onChangePassword: jest.fn(),
  onChangeTitle: jest.fn(),
  onChangeContents: jest.fn(),
  onClickSubmit: jest.fn(),
  onClickUpdate: jest.fn(),
  onClose: jest.fn(),
};
